# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SourceMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('page_count', models.IntegerField()),
                ('lines_per_page', models.IntegerField()),
                ('line_height', models.FloatField()),
                ('catalogue_ref', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransationEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('reattributed', models.BooleanField()),
                ('purchase_pounds', models.IntegerField()),
                ('purchase_shillings', models.IntegerField()),
                ('purchase_pence', models.FloatField()),
                ('standardised_purchase_price', models.FloatField()),
                ('target_pounds', models.IntegerField()),
                ('target_shillings', models.IntegerField()),
                ('target_pence', models.FloatField()),
                ('standardised_target_price', models.FloatField()),
                ('sold_pounds', models.IntegerField()),
                ('sold_shillings', models.IntegerField()),
                ('sold_pence', models.FloatField()),
                ('standardised_sold_price', models.FloatField()),
                ('entry_line', models.IntegerField()),
                ('entry_page', models.IntegerField()),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Artist', to='archives.Person')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='archives.Person')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='archives.Person')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='archives.Person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.SourceMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Person')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Shape')),
                ('subject_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Location')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Support')),
            ],
        ),
        migrations.AddField(
            model_name='transationevents',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Work'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Title'),
        ),
    ]
