# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_location_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sourcematerial',
            options={'ordering': ['catalogue_ref']},
        ),
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Genre'),
        ),
    ]
