# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20170913_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transationevents',
            options={'verbose_name': 'Transaction event', 'verbose_name_plural': 'Transaction events'},
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Shape'),
        ),
        migrations.AlterField(
            model_name='work',
            name='subject_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Location'),
        ),
        migrations.AlterField(
            model_name='work',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Support'),
        ),
    ]
