# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20170914_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='transationevents',
            name='encoded_cost',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='purchase_pence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='purchase_pounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='purchase_shillings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='sold_pence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='sold_pounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='sold_shillings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='standardised_purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='standardised_target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='target_pence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='target_pounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='target_shillings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
