# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20170914_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transationevents',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Artist', to='archives.Person'),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='archives.Person'),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='archives.Person'),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='archives.Person'),
        ),
        migrations.AlterField(
            model_name='transationevents',
            name='standardised_sold_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
