# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_auto_20170914_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='transationevents',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
