# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_transationevents_sold_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('family_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='transationevents',
            options={'ordering': ('source', 'stock_number'), 'verbose_name': 'Transaction event', 'verbose_name_plural': 'Transaction events'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('artist__family_name', 'title')},
        ),
        migrations.AddField(
            model_name='person',
            name='ulan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
