# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_auto_20170918_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=b'page_images/')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.SourceMaterial')),
            ],
            options={
                'ordering': ['source__title', 'page_number'],
            },
        ),
    ]
