# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transationevents',
            name='page_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.PageImage'),
        ),
    ]
